/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Julian.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'Julian.view.MyViewportViewModel',
        'Julian.view.MyViewportViewController',
        'Ext.panel.Panel',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    controller: 'myviewport',
    viewModel: {
        type: 'myviewport'
    },
    height: 250,
    width: 400,
    layout: 'fit',

    items: [
        {
            xtype: 'panel',
            title: 'RecordRTC',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'label',
                    text: 'URL Ejemplos: https://www.webrtc-experiment.com/RecordRTC/'
                },
                {
                    xtype: 'label',
                    html: '<b>Estado...</b>',
                    itemId: 'labelEstado'
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'label',
                            flex: 1,
                            height: 510,
                            html: '<hr><div class="fondonegro">  <video id="video-boos" controls autoplay playsinline></video> </div><hr><footer style="margin-top: 20px;"><small id="send-message"></small></footer>',
                            itemId: 'labelVideo'
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            height: 30,
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnStart',
                                    text: 'Start Recording',
                                    listeners: {
                                        click: 'onBtnStartClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'btnStop',
                                    text: 'Stop Recording',
                                    listeners: {
                                        click: 'onBtnStopClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'btnCargar',
                                    text: 'Upload file',
                                    listeners: {
                                        click: 'onBtnUploadClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        render: 'onViewportRender'
    }

});